run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused constants, variables, functions

    # Additional recommended linters
    - gofmt         # Check formatting
    - gofumpt       # Stricter formatting (superset of gofmt)
    - goimports     # Check imports formatting
    - misspell      # Check for misspelled English words
    - revive        # Drop-in replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - gosec         # Security issues
    - bodyclose     # Check HTTP body is closed
    - errname       # Check error naming conventions
    - errorlint     # Check error wrapping
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Check cyclomatic complexity
    - dupl          # Check code duplication
    - gocritic      # Most opinionated Go linter
    - whitespace    # Check for unnecessary whitespace
    - stylecheck    # Stylecheck is a replacement for golint

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = func() to explicitly ignore errors

  govet:
    enable-all: true
    disable:
      - shadow  # Reports variables that shadow other variables

  gofumpt:
    extra-rules: true  # Enable additional formatting rules

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - whyNoLint

  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]  # Disable package comments and camelCase checks for now

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some linters from running on tests
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
