#!/usr/bin/env bash
#
# assign-ports.sh - Port assignment hook for dual
#
# This hook calculates and assigns ports for a newly created worktree.
# It uses hash-based port assignment to ensure deterministic, conflict-free ports.
#
# Environment variables provided by dual:
#   DUAL_EVENT         - The hook event (postWorktreeCreate)
#   DUAL_CONTEXT_NAME  - The name of the context (branch name)
#   DUAL_CONTEXT_PATH  - The absolute path to the worktree
#   DUAL_PROJECT_ROOT  - The absolute path to the main project

set -e  # Exit on error

echo "[assign-ports] Starting port assignment for context: ${DUAL_CONTEXT_NAME}"

# Configuration
MIN_PORT=4000
MAX_PORT=14000
PORT_RANGE=100  # Number of ports allocated per context
NUM_SLOTS=$(((MAX_PORT - MIN_PORT) / PORT_RANGE))  # Number of possible contexts (100)

# Function to calculate hash of a string
# Returns a number between 0 and NUM_SLOTS-1
calculate_hash() {
  local str="$1"
  # Use cksum for simple hash calculation (available on all Unix systems)
  # cksum outputs: checksum bytes filename
  # We take the checksum, modulo by NUM_SLOTS
  local hash=$(echo -n "$str" | cksum | awk '{print $1}')
  echo $((hash % NUM_SLOTS))
}

# Calculate base port using hash-based assignment
# This ensures the same context name always gets the same port
HASH=$(calculate_hash "${DUAL_CONTEXT_NAME}")
BASE_PORT=$((MIN_PORT + HASH * PORT_RANGE))

echo "[assign-ports] Context name: ${DUAL_CONTEXT_NAME}"
echo "[assign-ports] Hash value: ${HASH}"
echo "[assign-ports] Base port: ${BASE_PORT}"

# Calculate service-specific ports
# Each service gets an offset from the base port
WEB_PORT=$((BASE_PORT + 1))
API_PORT=$((BASE_PORT + 2))
WORKER_PORT=$((BASE_PORT + 3))

echo "[assign-ports] Port assignments:"
echo "[assign-ports]   Web:    ${WEB_PORT}"
echo "[assign-ports]   API:    ${API_PORT}"
echo "[assign-ports]   Worker: ${WORKER_PORT}"

# Store the base port in a file for use by other hooks
PORT_FILE="${DUAL_CONTEXT_PATH}/.dual-port"
cat > "${PORT_FILE}" << EOF
# Port assignment for context: ${DUAL_CONTEXT_NAME}
# Generated by assign-ports.sh on $(date)
BASE_PORT=${BASE_PORT}
WEB_PORT=${WEB_PORT}
API_PORT=${API_PORT}
WORKER_PORT=${WORKER_PORT}
EOF

echo "[assign-ports] Port information saved to: ${PORT_FILE}"
echo "[assign-ports] Port assignment complete!"

# Exit successfully
exit 0
