version: 1

# Services configuration
services:
  web:
    path: apps/web
    envFile: apps/web/.env
  api:
    path: apps/api
    envFile: apps/api/.env
  worker:
    path: apps/worker
    envFile: apps/worker/.env

# Worktree configuration
worktrees:
  # Path where worktrees will be created (relative to project root)
  path: ../worktrees
  # Naming pattern for worktree directories
  naming: "{branch}"

# Environment configuration
env:
  # Base environment file (optional)
  baseFile: .env.example

# Lifecycle hooks
hooks:
  # Hooks executed after a worktree is created
  postWorktreeCreate:
    - assign-ports.sh
    - setup-environment.sh

  # Hooks executed before a worktree is deleted
  preWorktreeDelete:
    # Add cleanup hooks here if needed

  # Hooks executed after a worktree is deleted
  postWorktreeDelete:
    # Add cleanup hooks here if needed
