#!/bin/bash
set -e

# Example hook: Set up environment files for the worktree
# Triggered by: postWorktreeCreate

echo "[Hook] Setting up environment files for context: $DUAL_CONTEXT_NAME"

# Create .env.local file in the worktree if it doesn't exist
ENV_FILE="$DUAL_CONTEXT_PATH/.env.local"

echo "[Hook] Writing environment configuration to: $ENV_FILE"

# Write environment configuration
cat > "$ENV_FILE" <<EOF
# Auto-generated by dual hooks
# Context: $DUAL_CONTEXT_NAME
# Generated: $(date)

# Context information
DUAL_CONTEXT=$DUAL_CONTEXT_NAME
DUAL_CONTEXT_PATH=$DUAL_CONTEXT_PATH

# Add your custom environment variables here
# For example:
# DATABASE_URL=postgresql://localhost:5432/myapp_$DUAL_CONTEXT_NAME
# REDIS_URL=redis://localhost:6379/$((RANDOM % 16))

# If you need port management, you can implement it here:
# BASE_PORT=4000
# CONTEXT_HASH=\$(echo -n "$DUAL_CONTEXT_NAME" | md5sum | cut -c1-4)
# PORT=\$((BASE_PORT + 0x\$CONTEXT_HASH % 1000))
# echo "PORT=\$PORT"

EOF

echo "[Hook] ✓ Environment file created: $ENV_FILE"
echo "[Hook]   You can customize this hook to add your own environment variables"
echo "[Hook] Environment setup complete"
