#!/bin/bash
set -e

# Example hook: Update environment files with assigned ports
# Triggered by: postPortAssign

echo "[Hook] Setting up environment files for context: $DUAL_CONTEXT_NAME"

# Create .env file in the worktree if it doesn't exist
ENV_FILE="$DUAL_CONTEXT_PATH/.env.local"

echo "[Hook] Writing port configuration to: $ENV_FILE"

# Write port configuration
cat > "$ENV_FILE" <<EOF
# Auto-generated by dual hooks
# Context: $DUAL_CONTEXT_NAME
# Generated: $(date)

# Base configuration
DUAL_CONTEXT=$DUAL_CONTEXT_NAME
DUAL_BASE_PORT=$DUAL_BASE_PORT

EOF

# Add service-specific ports
# The hook system exports DUAL_PORT_<SERVICE> for each service
for var in $(env | grep '^DUAL_PORT_' | sort); do
    echo "$var" >> "$ENV_FILE"
done

echo "[Hook] ✓ Environment file created: $ENV_FILE"
echo "[Hook] Environment setup complete"
